### ISSUE TITLE
Unable to take vpn backup from solace deployed in openshift

### ISSUE THREAD

**Issue by sandip22c** [flyisland/solconfig#7]
Hello @flyisland,

We have solace deployed in OpenShift docker.
And solconfig is failing while taking vpn backup from solace deployed in docker.
Please find below command logs.

https://raw.githubusercontent.com/sandip22c/raw_data/master/solace_backup/solace_1.jpg
https://raw.githubusercontent.com/sandip22c/raw_data/master/solace_backup/solace_2.jpg
https://raw.githubusercontent.com/sandip22c/raw_data/master/solace_backup/solace_3.jpg

Kindly suggest.

**Comment by flyisland** [comment]
Hi @sandip22c , could you access the solace broker using `curl` like `curl -k -u admin:admin https://xxxx//SEMP/v2/config/msgVpns/default`, then share with me the output

**Comment by sandip22c** [comment]
Hello @flyisland,

Please find below screenshots for the given curl command output.

https://raw.githubusercontent.com/sandip22c/raw_data/master/solace_backup/vpn1.jpg
https://raw.githubusercontent.com/sandip22c/raw_data/master/solace_backup/vpn2.jpg
https://raw.githubusercontent.com/sandip22c/raw_data/master/solace_backup/vpn3.jpg
https://raw.githubusercontent.com/sandip22c/raw_data/master/solace_backup/vpn4.jpg
https://raw.githubusercontent.com/sandip22c/raw_data/master/solace_backup/vpn5.jpg
https://raw.githubusercontent.com/sandip22c/raw_data/master/solace_backup/vpn6.jpg
https://raw.githubusercontent.com/sandip22c/raw_data/master/solace_backup/vpn7.jpg
https://raw.githubusercontent.com/sandip22c/raw_data/master/solace_backup/vpn8.jpg

**Comment by flyisland** [comment]
Hi @sandip22c, 
The exception "no subject alternative DNS name matching found" means the hostname inside the certificate doesn't match the actual URL you used to access the solace broker. 

Generally, you should ensure you used the correct certificate on the solace broker.

By design, the solconfig could run in "insecure" mode with the `-k` option, which means not verifying the server certificates, just like the `-k` option for the curl tool.

I'd like you to try below:
1.  Run the curl again without the `-k` option, to check if the curl reports the same error like "no subject alternative DNS name matching found" 
2. I saw you use a script named `solace_backup`, please use the `solconfig.jar` directly with the `-k` option, 
3. If you still got the exception on step 2, try `java -Djdk.internal.httpclient.disableHostnameVerification=true -jar ./solconfig.jar ...`

**Comment by sandip22c** [comment]
Hello @flyisland 
Let me check the solution as you suggested.

**Comment by flyisland** [comment]
@sandip22c any update?

**Comment by sandip22c** [comment]
Hello @flyisland,
Apologies for delayed response.

Tested the issue with jar file & found its working.
We can close the issue.
